In [279]:
from matplotlib import colors
import numpy as np
import pandas as pd
import json
import math

path_xray = "C:/Users/HP/Desktop/Curso de Python/Workspace/miweb/Astronomía/data_obtained.txt"
with open(path_xray, "r") as f:
    NGC6809_sources = json.load(f)
HC_score = 0.25
MV_XR_score = 0.25
optical_score = 0.5
df = pd.DataFrame(NGC6809_sources)
df["AB"] = float(0)
df["CV"] = float(0)
df["LMXRB"] = float(0)
df

,id,Hardness_classification,Xray source,Mv vs xray,pos_0,275 - 336,336_Mag,pos_1,438 - 606,606_Mag,pos_2,606 - 814,814_Mag,radius,#sources,AB,CV,LMXRB
0,CX2_1,CV & AB,CX2,CV,MS,1.5019,21.5343,MS,1.0964,20.4450,MS,0.7717,19.6733,0.6,1,0.0,0.0,0.0
1,CX8_1,CV & AB,CX8,AB,bluer than MS L1,0.8844,17.5024,Red giant branch,0.9845,16.6808,Red giant branch,0.7291,15.9517,0.6,1,0.0,0.0,0.0
2,CX9_1,CV & AB,CX9,AB,bluer than MS L1,0.5231,17.8890,bluer than MS L1,0.5940,17.5223,bluer than MS L1,0.5163,17.0060,2,6,0.0,0.0,0.0
3,CX9_2,CV & AB,CX9,AB,MSTO,0.6434,17.8927,MS,0.6786,17.4505,MS,0.5864,16.8641,2,6,0.0,0.0,0.0
4,CX9_3,CV & AB,CX9,CV,MS,1.6307,21.8747,MS,1.2093,20.5491,MS,0.8173,19.7318,2,6,0.0,0.0,0.0
5,CX9_4,CV & AB,CX9,CV,MS,1.7096,21.3682,MS,1.1121,20.3108,MS,0.7835,19.5273,2,6,0.0,0.0,0.0
6,CX9_5,CV & AB,CX9,CV,MS,1.4877,21.2895,MS,1.1386,20.2866,MS,0.7681,19.5185,2,6,0.0,0.0,0.0
7,CX9_6,CV & AB,CX9,AB,MS,0.8743,19.9259,MS,0.8508,19.3930,MS,0.6668,18.7262,2,6,0.0,0.0,0.0
8,CX11_1,CV & AB,CX11,AB,MS,1.1918,20.9660,MS,1.0411,20.0250,MS,0.6837,19.3413,0.6,2,0.0,0.0,0.0
9,CX11_2,CV & AB,CX11,AB,MS,0.7644,19.2042,MS,0.8172,18.8580,MS,0.5997,18.2583,0.6,2,0.0,0.0,0.0
10,CX13_1,CV & AB,CX13,AB,MS,0.8480,20.2066,MS,0.8098,19.5630,MS,0.6798,18.8832,2,2,0.0,0.0,0.0
11,CX13_2,CV & AB,CX13,AB,MS,0.6756,18.9232,MS,0.7976,18.5249,MS,0.5959,17.9290,2,2,0.0,0.0,0.0

In [280]:
for i in range(len(df)):
    
    HC = df.iloc[i]["Hardness_classification"]
    MV_XRAY = df.iloc[i]["Mv vs xray"]
    
    if HC == "LMXRB":
        df.loc[i, "LMXRB"] += HC_score
    elif HC == "CV":
        df.loc[i, "CV"] += HC_score
    elif HC == "CV & AB":
        df.loc[i, "CV"] += HC_score/2
        df.loc[i, "AB"] += HC_score/2
    elif HC == "AB":
        df.loc[i, "AB"] += HC_score

df

,id,Hardness_classification,Xray source,Mv vs xray,pos_0,275 - 336,336_Mag,pos_1,438 - 606,606_Mag,pos_2,606 - 814,814_Mag,radius,#sources,AB,CV,LMXRB
0,CX2_1,CV & AB,CX2,CV,MS,1.5019,21.5343,MS,1.0964,20.4450,MS,0.7717,19.6733,0.6,1,0.125,0.125,0.0
1,CX8_1,CV & AB,CX8,AB,bluer than MS L1,0.8844,17.5024,Red giant branch,0.9845,16.6808,Red giant branch,0.7291,15.9517,0.6,1,0.125,0.125,0.0
2,CX9_1,CV & AB,CX9,AB,bluer than MS L1,0.5231,17.8890,bluer than MS L1,0.5940,17.5223,bluer than MS L1,0.5163,17.0060,2,6,0.125,0.125,0.0
3,CX9_2,CV & AB,CX9,AB,MSTO,0.6434,17.8927,MS,0.6786,17.4505,MS,0.5864,16.8641,2,6,0.125,0.125,0.0
4,CX9_3,CV & AB,CX9,CV,MS,1.6307,21.8747,MS,1.2093,20.5491,MS,0.8173,19.7318,2,6,0.125,0.125,0.0
5,CX9_4,CV & AB,CX9,CV,MS,1.7096,21.3682,MS,1.1121,20.3108,MS,0.7835,19.5273,2,6,0.125,0.125,0.0
6,CX9_5,CV & AB,CX9,CV,MS,1.4877,21.2895,MS,1.1386,20.2866,MS,0.7681,19.5185,2,6,0.125,0.125,0.0
7,CX9_6,CV & AB,CX9,AB,MS,0.8743,19.9259,MS,0.8508,19.3930,MS,0.6668,18.7262,2,6,0.125,0.125,0.0
8,CX11_1,CV & AB,CX11,AB,MS,1.1918,20.9660,MS,1.0411,20.0250,MS,0.6837,19.3413,0.6,2,0.125,0.125,0.0
9,CX11_2,CV & AB,CX11,AB,MS,0.7644,19.2042,MS,0.8172,18.8580,MS,0.5997,18.2583,0.6,2,0.125,0.125,0.0
10,CX13_1,CV & AB,CX13,AB,MS,0.8480,20.2066,MS,0.8098,19.5630,MS,0.6798,18.8832,2,2,0.125,0.125,0.0
11,CX13_2,CV & AB,CX13,AB,MS,0.6756,18.9232,MS,0.7976,18.5249,MS,0.5959,17.9290,2,2,0.125,0.125,0.0

In [281]:
for i in range(len(df)):
    HC = df.iloc[i]["Hardness_classification"]
    MV_XRAY = df.iloc[i]["Mv vs xray"]
    
    if MV_XRAY == "LMXRB":
        df.loc[i, "LMXRB"] += MV_XR_score
    elif MV_XRAY == "CV":
        df.loc[i, "CV"] += MV_XR_score
    elif MV_XRAY == "AB":
        df.loc[i, "AB"] += MV_XR_score

df

,id,Hardness_classification,Xray source,Mv vs xray,pos_0,275 - 336,336_Mag,pos_1,438 - 606,606_Mag,pos_2,606 - 814,814_Mag,radius,#sources,AB,CV,LMXRB
0,CX2_1,CV & AB,CX2,CV,MS,1.5019,21.5343,MS,1.0964,20.4450,MS,0.7717,19.6733,0.6,1,0.125,0.375,0.0
1,CX8_1,CV & AB,CX8,AB,bluer than MS L1,0.8844,17.5024,Red giant branch,0.9845,16.6808,Red giant branch,0.7291,15.9517,0.6,1,0.375,0.125,0.0
2,CX9_1,CV & AB,CX9,AB,bluer than MS L1,0.5231,17.8890,bluer than MS L1,0.5940,17.5223,bluer than MS L1,0.5163,17.0060,2,6,0.375,0.125,0.0
3,CX9_2,CV & AB,CX9,AB,MSTO,0.6434,17.8927,MS,0.6786,17.4505,MS,0.5864,16.8641,2,6,0.375,0.125,0.0
4,CX9_3,CV & AB,CX9,CV,MS,1.6307,21.8747,MS,1.2093,20.5491,MS,0.8173,19.7318,2,6,0.125,0.375,0.0
5,CX9_4,CV & AB,CX9,CV,MS,1.7096,21.3682,MS,1.1121,20.3108,MS,0.7835,19.5273,2,6,0.125,0.375,0.0
6,CX9_5,CV & AB,CX9,CV,MS,1.4877,21.2895,MS,1.1386,20.2866,MS,0.7681,19.5185,2,6,0.125,0.375,0.0
7,CX9_6,CV & AB,CX9,AB,MS,0.8743,19.9259,MS,0.8508,19.3930,MS,0.6668,18.7262,2,6,0.375,0.125,0.0
8,CX11_1,CV & AB,CX11,AB,MS,1.1918,20.9660,MS,1.0411,20.0250,MS,0.6837,19.3413,0.6,2,0.375,0.125,0.0
9,CX11_2,CV & AB,CX11,AB,MS,0.7644,19.2042,MS,0.8172,18.8580,MS,0.5997,18.2583,0.6,2,0.375,0.125,0.0
10,CX13_1,CV & AB,CX13,AB,MS,0.8480,20.2066,MS,0.8098,19.5630,MS,0.6798,18.8832,2,2,0.375,0.125,0.0
11,CX13_2,CV & AB,CX13,AB,MS,0.6756,18.9232,MS,0.7976,18.5249,MS,0.5959,17.9290,2,2,0.375,0.125,0.0

In [282]:
for i in range(len(df)):
    HC = df.iloc[i]["Hardness_classification"]
    MV_XRAY = df.iloc[i]["Mv vs xray"]
    for j in range(3):
        pos = df.iloc[i][f"pos_{j}"]
        if pos == "bluer than MS L1":
            if df.iloc[i]["LMXRB"] > df.iloc[i]["CV"]:
                if df.iloc[i]["LMXRB"] > df.iloc[i]["AB"]:
                    df.loc[i, "LMXRB"] += (optical_score-(optical_score/6)*(j-1))/3
                else:
                    df.loc[i, "LMXRB"] += (optical_score-(optical_score/6)*(j-1))/5
            elif df.iloc[i]["LMXRB"] < df.iloc[i]["CV"]:
                if df.iloc[i]["CV"] > df.iloc[i]["AB"]:
                    df.loc[i, "CV"] += (optical_score-(optical_score/6)*(j-1))/3
                else:
                    df.loc[i, "CV"] += (optical_score-(optical_score/6)*(j-1))/5
            else:
                df.loc[i, "LMXRB"] += optical_score/6
                df.loc[i, "CV"] += optical_score/6
        elif pos == "redder than MS L1" or pos == "sub-sub-giant branch" or pos == "Red giant branch":
            if df.iloc[i]["AB"] > df.iloc[i]["CV"] and df.iloc[i]["AB"] > df.iloc[i]["LMXRB"]:
                df.loc[i, "AB"] += (optical_score+(optical_score/6)*(j-1))/3
            else:
                df.loc[i, "AB"] += (optical_score+(optical_score/6)*(j-1))/5
        elif pos == "MS" or pos == "MSTO":
            if df.iloc[i]["AB"] > df.iloc[i]["CV"] and df.iloc[i]["AB"] > df.iloc[i]["LMXRB"]:
                df.loc[i, "AB"] += optical_score/6

df

,id,Hardness_classification,Xray source,Mv vs xray,pos_0,275 - 336,336_Mag,pos_1,438 - 606,606_Mag,pos_2,606 - 814,814_Mag,radius,#sources,AB,CV,LMXRB
0,CX2_1,CV & AB,CX2,CV,MS,1.5019,21.5343,MS,1.0964,20.4450,MS,0.7717,19.6733,0.6,1,0.125000,0.375000,0.0
1,CX8_1,CV & AB,CX8,AB,bluer than MS L1,0.8844,17.5024,Red giant branch,0.9845,16.6808,Red giant branch,0.7291,15.9517,0.6,1,0.736111,0.241667,0.0
2,CX9_1,CV & AB,CX9,AB,bluer than MS L1,0.5231,17.8890,bluer than MS L1,0.5940,17.5223,bluer than MS L1,0.5163,17.0060,2,6,0.375000,0.425000,0.0
3,CX9_2,CV & AB,CX9,AB,MSTO,0.6434,17.8927,MS,0.6786,17.4505,MS,0.5864,16.8641,2,6,0.625000,0.125000,0.0
4,CX9_3,CV & AB,CX9,CV,MS,1.6307,21.8747,MS,1.2093,20.5491,MS,0.8173,19.7318,2,6,0.125000,0.375000,0.0
5,CX9_4,CV & AB,CX9,CV,MS,1.7096,21.3682,MS,1.1121,20.3108,MS,0.7835,19.5273,2,6,0.125000,0.375000,0.0
6,CX9_5,CV & AB,CX9,CV,MS,1.4877,21.2895,MS,1.1386,20.2866,MS,0.7681,19.5185,2,6,0.125000,0.375000,0.0
7,CX9_6,CV & AB,CX9,AB,MS,0.8743,19.9259,MS,0.8508,19.3930,MS,0.6668,18.7262,2,6,0.625000,0.125000,0.0
8,CX11_1,CV & AB,CX11,AB,MS,1.1918,20.9660,MS,1.0411,20.0250,MS,0.6837,19.3413,0.6,2,0.625000,0.125000,0.0
9,CX11_2,CV & AB,CX11,AB,MS,0.7644,19.2042,MS,0.8172,18.8580,MS,0.5997,18.2583,0.6,2,0.625000,0.125000,0.0
10,CX13_1,CV & AB,CX13,AB,MS,0.8480,20.2066,MS,0.8098,19.5630,MS,0.6798,18.8832,2,2,0.625000,0.125000,0.0
11,CX13_2,CV & AB,CX13,AB,MS,0.6756,18.9232,MS,0.7976,18.5249,MS,0.5959,17.9290,2,2,0.625000,0.125000,0.0

In [283]:
df["posibility_counterpart"] = df["AB"] + df["CV"] + df["LMXRB"]
df

,id,Hardness_classification,Xray source,Mv vs xray,pos_0,275 - 336,336_Mag,pos_1,438 - 606,606_Mag,pos_2,606 - 814,814_Mag,radius,#sources,AB,CV,LMXRB,posibility_counterpart
0,CX2_1,CV & AB,CX2,CV,MS,1.5019,21.5343,MS,1.0964,20.4450,MS,0.7717,19.6733,0.6,1,0.125000,0.375000,0.0,0.500000
1,CX8_1,CV & AB,CX8,AB,bluer than MS L1,0.8844,17.5024,Red giant branch,0.9845,16.6808,Red giant branch,0.7291,15.9517,0.6,1,0.736111,0.241667,0.0,0.977778
2,CX9_1,CV & AB,CX9,AB,bluer than MS L1,0.5231,17.8890,bluer than MS L1,0.5940,17.5223,bluer than MS L1,0.5163,17.0060,2,6,0.375000,0.425000,0.0,0.800000
3,CX9_2,CV & AB,CX9,AB,MSTO,0.6434,17.8927,MS,0.6786,17.4505,MS,0.5864,16.8641,2,6,0.625000,0.125000,0.0,0.750000
4,CX9_3,CV & AB,CX9,CV,MS,1.6307,21.8747,MS,1.2093,20.5491,MS,0.8173,19.7318,2,6,0.125000,0.375000,0.0,0.500000
5,CX9_4,CV & AB,CX9,CV,MS,1.7096,21.3682,MS,1.1121,20.3108,MS,0.7835,19.5273,2,6,0.125000,0.375000,0.0,0.500000
6,CX9_5,CV & AB,CX9,CV,MS,1.4877,21.2895,MS,1.1386,20.2866,MS,0.7681,19.5185,2,6,0.125000,0.375000,0.0,0.500000
7,CX9_6,CV & AB,CX9,AB,MS,0.8743,19.9259,MS,0.8508,19.3930,MS,0.6668,18.7262,2,6,0.625000,0.125000,0.0,0.750000
8,CX11_1,CV & AB,CX11,AB,MS,1.1918,20.9660,MS,1.0411,20.0250,MS,0.6837,19.3413,0.6,2,0.625000,0.125000,0.0,0.750000
9,CX11_2,CV & AB,CX11,AB,MS,0.7644,19.2042,MS,0.8172,18.8580,MS,0.5997,18.2583,0.6,2,0.625000,0.125000,0.0,0.750000
10,CX13_1,CV & AB,CX13,AB,MS,0.8480,20.2066,MS,0.8098,19.5630,MS,0.6798,18.8832,2,2,0.625000,0.125000,0.0,0.750000
11,CX13_2,CV & AB,CX13,AB,MS,0.6756,18.9232,MS,0.7976,18.5249,MS,0.5959,17.9290,2,2,0.625000,0.125000,0.0,0.750000

In [284]:
df["posibility_not_counterpart"] = 1 - df["posibility_counterpart"]
total_posibility = 1 - df.groupby("Xray source")["posibility_not_counterpart"].prod()

for i in range(len(df)):
    array = np.array([df.iloc[i]["AB"], df.iloc[i]["CV"], df.iloc[i]["LMXRB"]])
    sorted_array = sorted(array, reverse=True)
    if sorted_array[1] != 0:
        min_rate = sorted_array[0]/sorted_array[1]
    else:
        min_rate = 1000000000
    df.loc[i, "posibility_counterpart_weighted"] = df.iloc[i]["posibility_counterpart"]*min_rate
sum_after = df.groupby("Xray source")["posibility_counterpart_weighted"].sum()
for i in range(len(df)):
    df.loc[i, "posibility_counterpart_new"] = df.loc[i, "posibility_counterpart_weighted"] * total_posibility.loc[df.iloc[i]["Xray source"]] / sum_after.loc[df.iloc[i]["Xray source"]]
df

,id,Hardness_classification,Xray source,Mv vs xray,pos_0,275 - 336,336_Mag,pos_1,438 - 606,606_Mag,...,814_Mag,radius,#sources,AB,CV,LMXRB,posibility_counterpart,posibility_not_counterpart,posibility_counterpart_weighted,posibility_counterpart_new
0,CX2_1,CV & AB,CX2,CV,MS,1.5019,21.5343,MS,1.0964,20.4450,...,19.6733,0.6,1,0.125000,0.375000,0.0,0.500000,0.500000,1.500000,0.500000
1,CX8_1,CV & AB,CX8,AB,bluer than MS L1,0.8844,17.5024,Red giant branch,0.9845,16.6808,...,15.9517,0.6,1,0.736111,0.241667,0.0,0.977778,0.022222,2.978289,0.977778
2,CX9_1,CV & AB,CX9,AB,bluer than MS L1,0.5231,17.8890,bluer than MS L1,0.5940,17.5223,...,17.0060,2,6,0.375000,0.425000,0.0,0.800000,0.200000,0.906667,0.070138
3,CX9_2,CV & AB,CX9,AB,MSTO,0.6434,17.8927,MS,0.6786,17.4505,...,16.8641,2,6,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.290094
4,CX9_3,CV & AB,CX9,CV,MS,1.6307,21.8747,MS,1.2093,20.5491,...,19.7318,2,6,0.125000,0.375000,0.0,0.500000,0.500000,1.500000,0.116037
5,CX9_4,CV & AB,CX9,CV,MS,1.7096,21.3682,MS,1.1121,20.3108,...,19.5273,2,6,0.125000,0.375000,0.0,0.500000,0.500000,1.500000,0.116037
6,CX9_5,CV & AB,CX9,CV,MS,1.4877,21.2895,MS,1.1386,20.2866,...,19.5185,2,6,0.125000,0.375000,0.0,0.500000,0.500000,1.500000,0.116037
7,CX9_6,CV & AB,CX9,AB,MS,0.8743,19.9259,MS,0.8508,19.3930,...,18.7262,2,6,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.290094
8,CX11_1,CV & AB,CX11,AB,MS,1.1918,20.9660,MS,1.0411,20.0250,...,19.3413,0.6,2,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.468750
9,CX11_2,CV & AB,CX11,AB,MS,0.7644,19.2042,MS,0.8172,18.8580,...,18.2583,0.6,2,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.468750
10,CX13_1,CV & AB,CX13,AB,MS,0.8480,20.2066,MS,0.8098,19.5630,...,18.8832,2,2,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.468750
11,CX13_2,CV & AB,CX13,AB,MS,0.6756,18.9232,MS,0.7976,18.5249,...,17.9290,2,2,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.468750

In [285]:
for i in range(len(df)):
    if df.iloc[i]["radius"] == '2':
        df.loc[i, "posibility_counterpart_new"] *= 0.8
df

,id,Hardness_classification,Xray source,Mv vs xray,pos_0,275 - 336,336_Mag,pos_1,438 - 606,606_Mag,...,814_Mag,radius,#sources,AB,CV,LMXRB,posibility_counterpart,posibility_not_counterpart,posibility_counterpart_weighted,posibility_counterpart_new
0,CX2_1,CV & AB,CX2,CV,MS,1.5019,21.5343,MS,1.0964,20.4450,...,19.6733,0.6,1,0.125000,0.375000,0.0,0.500000,0.500000,1.500000,0.500000
1,CX8_1,CV & AB,CX8,AB,bluer than MS L1,0.8844,17.5024,Red giant branch,0.9845,16.6808,...,15.9517,0.6,1,0.736111,0.241667,0.0,0.977778,0.022222,2.978289,0.977778
2,CX9_1,CV & AB,CX9,AB,bluer than MS L1,0.5231,17.8890,bluer than MS L1,0.5940,17.5223,...,17.0060,2,6,0.375000,0.425000,0.0,0.800000,0.200000,0.906667,0.056111
3,CX9_2,CV & AB,CX9,AB,MSTO,0.6434,17.8927,MS,0.6786,17.4505,...,16.8641,2,6,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.232075
4,CX9_3,CV & AB,CX9,CV,MS,1.6307,21.8747,MS,1.2093,20.5491,...,19.7318,2,6,0.125000,0.375000,0.0,0.500000,0.500000,1.500000,0.092830
5,CX9_4,CV & AB,CX9,CV,MS,1.7096,21.3682,MS,1.1121,20.3108,...,19.5273,2,6,0.125000,0.375000,0.0,0.500000,0.500000,1.500000,0.092830
6,CX9_5,CV & AB,CX9,CV,MS,1.4877,21.2895,MS,1.1386,20.2866,...,19.5185,2,6,0.125000,0.375000,0.0,0.500000,0.500000,1.500000,0.092830
7,CX9_6,CV & AB,CX9,AB,MS,0.8743,19.9259,MS,0.8508,19.3930,...,18.7262,2,6,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.232075
8,CX11_1,CV & AB,CX11,AB,MS,1.1918,20.9660,MS,1.0411,20.0250,...,19.3413,0.6,2,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.468750
9,CX11_2,CV & AB,CX11,AB,MS,0.7644,19.2042,MS,0.8172,18.8580,...,18.2583,0.6,2,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.468750
10,CX13_1,CV & AB,CX13,AB,MS,0.8480,20.2066,MS,0.8098,19.5630,...,18.8832,2,2,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.375000
11,CX13_2,CV & AB,CX13,AB,MS,0.6756,18.9232,MS,0.7976,18.5249,...,17.9290,2,2,0.625000,0.125000,0.0,0.750000,0.250000,3.750000,0.375000

In [286]:
df["AB"] *= df["posibility_counterpart_new"]/df["posibility_counterpart"]
df["CV"] *= df["posibility_counterpart_new"]/df["posibility_counterpart"]
df["LMXRB"] *= df["posibility_counterpart_new"]/df["posibility_counterpart"]
df.drop(columns = ["posibility_counterpart", "posibility_not_counterpart", "posibility_counterpart_weighted"],inplace = True)

prob_sum = df.groupby("Xray source")["posibility_counterpart_new"].sum()
for i in range(len(df)):
    df.loc[i,"total_prob"] = prob_sum.loc[df.loc[i, "Xray source"]]
df

,id,Hardness_classification,Xray source,Mv vs xray,pos_0,275 - 336,336_Mag,pos_1,438 - 606,606_Mag,pos_2,606 - 814,814_Mag,radius,#sources,AB,CV,LMXRB,posibility_counterpart_new,total_prob
0,CX2_1,CV & AB,CX2,CV,MS,1.5019,21.5343,MS,1.0964,20.4450,MS,0.7717,19.6733,0.6,1,0.125000,0.375000,0.0,0.500000,0.500000
1,CX8_1,CV & AB,CX8,AB,bluer than MS L1,0.8844,17.5024,Red giant branch,0.9845,16.6808,Red giant branch,0.7291,15.9517,0.6,1,0.736111,0.241667,0.0,0.977778,0.977778
2,CX9_1,CV & AB,CX9,AB,bluer than MS L1,0.5231,17.8890,bluer than MS L1,0.5940,17.5223,bluer than MS L1,0.5163,17.0060,2,6,0.026302,0.029809,0.0,0.056111,0.798750
3,CX9_2,CV & AB,CX9,AB,MSTO,0.6434,17.8927,MS,0.6786,17.4505,MS,0.5864,16.8641,2,6,0.193396,0.038679,0.0,0.232075,0.798750
4,CX9_3,CV & AB,CX9,CV,MS,1.6307,21.8747,MS,1.2093,20.5491,MS,0.8173,19.7318,2,6,0.023207,0.069622,0.0,0.092830,0.798750
5,CX9_4,CV & AB,CX9,CV,MS,1.7096,21.3682,MS,1.1121,20.3108,MS,0.7835,19.5273,2,6,0.023207,0.069622,0.0,0.092830,0.798750
6,CX9_5,CV & AB,CX9,CV,MS,1.4877,21.2895,MS,1.1386,20.2866,MS,0.7681,19.5185,2,6,0.023207,0.069622,0.0,0.092830,0.798750
7,CX9_6,CV & AB,CX9,AB,MS,0.8743,19.9259,MS,0.8508,19.3930,MS,0.6668,18.7262,2,6,0.193396,0.038679,0.0,0.232075,0.798750
8,CX11_1,CV & AB,CX11,AB,MS,1.1918,20.9660,MS,1.0411,20.0250,MS,0.6837,19.3413,0.6,2,0.390625,0.078125,0.0,0.468750,0.937500
9,CX11_2,CV & AB,CX11,AB,MS,0.7644,19.2042,MS,0.8172,18.8580,MS,0.5997,18.2583,0.6,2,0.390625,0.078125,0.0,0.468750,0.937500
10,CX13_1,CV & AB,CX13,AB,MS,0.8480,20.2066,MS,0.8098,19.5630,MS,0.6798,18.8832,2,2,0.312500,0.062500,0.0,0.375000,0.750000
11,CX13_2,CV & AB,CX13,AB,MS,0.6756,18.9232,MS,0.7976,18.5249,MS,0.5959,17.9290,2,2,0.312500,0.062500,0.0,0.375000,0.750000

In [287]:
df["AB(%)"] = round(df["AB"] * 100, 1)
df["CV(%)"] = round(df["CV"] * 100, 1)
df["LMXRB(%)"] = round(df["LMXRB"] * 100, 1)
df["posibility_counterpart_new(%)"] = round(df["posibility_counterpart_new"] * 100, 1)
df["total_prob(%)"] = round(df["total_prob"] * 100, 1)
df_final = df[["id", "AB(%)", "CV(%)", "LMXRB(%)", "posibility_counterpart_new(%)", "total_prob(%)"]]
df_final

,id,AB(%),CV(%),LMXRB(%),posibility_counterpart_new(%),total_prob(%)
0,CX2_1,12.5,37.5,0.0,50.0,50.0
1,CX8_1,73.6,24.2,0.0,97.8,97.8
2,CX9_1,2.6,3.0,0.0,5.6,79.9
3,CX9_2,19.3,3.9,0.0,23.2,79.9
4,CX9_3,2.3,7.0,0.0,9.3,79.9
5,CX9_4,2.3,7.0,0.0,9.3,79.9
6,CX9_5,2.3,7.0,0.0,9.3,79.9
7,CX9_6,19.3,3.9,0.0,23.2,79.9
8,CX11_1,39.1,7.8,0.0,46.9,93.8
9,CX11_2,39.1,7.8,0.0,46.9,93.8
10,CX13_1,31.2,6.2,0.0,37.5,75.0
11,CX13_2,31.2,6.2,0.0,37.5,75.0